experiment_name: arabic_finetune_from_pretrained
train_data: easyocr_data/arabic_train
valid_data: easyocr_data/arabic_val
select_data: /
batch_ratio: "1.0"
total_data_usage_ratio: 1.0
batch_size: 24
valInterval: 400
num_iter: 39500
saved_model: 'USER_HOME/.EasyOCR/model/arabic.pth'
FT: True
new_prediction: True
optim: adadelta
lr: 1.0

# Image parameters
imgH: 64
imgW: 640
rgb: False
PAD: True

# Model architecture (MATCHES arabic_g1 = None-ResNet-BiLSTM-CTC)
Transformation: None
FeatureExtraction: ResNet
SequenceModeling: BiLSTM
Prediction: CTC
decode: 'greedy'
num_fiducial: 20
input_channel: 1
output_channel: 512
hidden_size: 512

# Characters (Extracted from check_chars.py)
character: " !\"'()-.34:[]|«»،؟ءآأؤإئابةتثجحخدذرزسشصضطظعغـفقكلمنهوىئًٌٍَُِّْ٠١٢٣٤٥٦٧٨٩ٰپچڈژکگںھۀہۃیے۰۱۲۳۴۵۶۷•ﮋ﴿ﷲ"

# Data processing
batch_max_length: 192
sensitive: True
data_filtering_off: True
workers: 4
